stack:
  - python 2.7.16
  - python 3.4.9
  - python 3.5.7
  - python 3.6.8
  - python 3.7.0
  - python 3.7.1
  - python 3.7.2
  - python 3.7.3
  - python 3.7.4
  - python 3.8.0
  
init:
 - appveyor version
 - ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 
test_script:
- sh: |
    python --version
    python -c 'import sys; print (sys.version_info)'

build: off
