stack:
  - python 2.7.16
  - python 3.4.9
  - python 3.5.6
  - python 3.6.8
  - python 3.7.0
  - python 3.7.1
  - python 3.7.2
  - python 3.8.0
  
init:
- appveyor version

test_script:
- sh: |
    python --version
    python -c 'import sys; print (sys.version_info)'

build: off
