stack:
  - python 2.7.14
  - python 3.4.8
  - python 3.5.5
  - python 3.6.4
  
init:
- appveyor version

test_script:
- sh: |
    python --version
    python -c 'import yaml; import sys; print sys.version_info'

build: off
