stack:
  - ${PYTHON_STACK}

init:
 - appveyor version
 - ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud."
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 
test_script:
- sh: |
    python --version
    python -c 'import sys; print (sys.version_info)'
# try to upgrade pip before pytest install
- sh: python -m ensurepip --upgrade
- sh: python -m pip install --upgrade setuptools
- sh: pip install pytest

build: off

on_failure:
  - ls -ld $HOME/venv*
  - ls -ld $HOME/.localpython*
  - ls -ld $HOME/Python*
  - du -hs $HOME/venv*
  - du -hs $HOME/.localpython*
  
