stack:
  - python 2.7.15
  - python 3.4.8
  - python 3.5.5
  - python 3.6.6
  - python 3.7
  
init:
- appveyor version

test_script:
- sh: |
    python --version
    python -c 'import sys; print (sys.version_info)'

build: off
